'use client'
import {useEffect,useState} from 'react'
import {useParams,useRouter} from 'next/navigation'

type Stop={location_id:string;custom:string}
export default function Vehicle(){
  const {plate}=useParams<{plate:string}>();const decoded=decodeURIComponent(plate);const r=useRouter();
  const [users,setUsers]=useState<any[]>([]),[locations,setLocations]=useState<any[]>([]),[purposes,setPurposes]=useState<any[]>([]),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false)
  const [form,setForm]=useState<any>({usage_date:new Date().toISOString().slice(0,10),user_id:'',custom_user_name:'',start_location_id:'',start_location_custom:'',end_location_id:'',end_location_custom:'',start_time:'',end_time:'',start_mileage:'',end_mileage:'',purpose_ids:[],fuel_mileage:'',fuel_cost:'',remarks:'',stops:[] as Stop[]})
  useEffect(()=>{fetch('/api/meta').then(x=>x.json()).then(j=>{setUsers(j.users||[]);setLocations(j.locations||[]);setPurposes(j.purposes||[])})},[])
  const upd=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}))
  const toggle=(id:number)=>upd('purpose_ids',form.purpose_ids.includes(id)?form.purpose_ids.filter((x:number)=>x!==id):[...form.purpose_ids,id])
  const addStop=()=>upd('stops',[...form.stops,{location_id:'',custom:''}])
  async function submit(e:any){e.preventDefault();if(!form.purpose_ids.length){setMsg('請至少選擇一項用途');return}setSaving(true);setMsg('');try{const res=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plate:decoded,...form})});const j=await res.json();if(!res.ok)throw new Error(j.error||'儲存失敗');setMsg('已儲存。系統會依車牌＋日期自動彙整。');setForm((x:any)=>({...x,start_time:'',end_time:'',start_mileage:'',end_mileage:'',purpose_ids:[],fuel_mileage:'',fuel_cost:'',remarks:'',stops:[]}))}catch(err:any){setMsg(err.message||'儲存失敗')}finally{setSaving(false)}}
  return <main className="container"><div className="toolbar"><div><button className="btn" onClick={()=>r.push('/dashboard')}>← 返回</button><h1>{decoded}</h1></div><button className="btn" onClick={()=>r.push(`/dashboard/records?plate=${encodeURIComponent(decoded)}`)}>查看本車紀錄</button></div>{msg&&<div className={'notice '+(msg.includes('失敗')||msg.includes('請至少')?'error':'')}>{msg}</div>}<form className="card" onSubmit={submit}>
    <div className="row"><div className="field"><label>使用日期 *</label><input type="date" value={form.usage_date} onChange={e=>upd('usage_date',e.target.value)} required/></div><div className="field"><label>使用人 *</label><select value={form.user_id} onChange={e=>upd('user_id',e.target.value)} required><option value="">請選擇</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}<option value="__custom">其他（自行輸入）</option></select>{form.user_id==='__custom'&&<input placeholder="請輸入姓名" value={form.custom_user_name} onChange={e=>upd('custom_user_name',e.target.value)} required/>}</div></div>
    <div className="row"><div className="field"><label>出發地點 *</label><select value={form.start_location_id} onChange={e=>upd('start_location_id',e.target.value)} required><option value="">請選擇</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}<option value="__custom">其他（自行輸入）</option></select>{form.start_location_id==='__custom'&&<input placeholder="請輸入地點" value={form.start_location_custom} onChange={e=>upd('start_location_custom',e.target.value)} required/>}</div><div className="field"><label>結束地點 *</label><select value={form.end_location_id} onChange={e=>upd('end_location_id',e.target.value)} required><option value="">請選擇</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}<option value="__custom">其他（自行輸入）</option></select>{form.end_location_id==='__custom'&&<input placeholder="請輸入地點" value={form.end_location_custom} onChange={e=>upd('end_location_custom',e.target.value)} required/>}</div></div>
    <div style={{marginBottom:18}}><button type="button" className="btn" onClick={addStop}>＋增加中途地點</button>{form.stops.map((s:Stop,i:number)=><div className="row3" key={i} style={{marginTop:10}}><div className="field"><label>中途地點 {i+1}</label><select value={s.location_id} onChange={e=>{const a=[...form.stops];a[i]={...a[i],location_id:e.target.value};upd('stops',a)}}><option value="">請選擇</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}<option value="__custom">其他（自行輸入）</option></select>{s.location_id==='__custom'&&<input placeholder="請輸入地點" value={s.custom} onChange={e=>{const a=[...form.stops];a[i]={...a[i],custom:e.target.value};upd('stops',a)}} required/>}</div><div></div><button type="button" className="btn danger" onClick={()=>upd('stops',form.stops.filter((_:any,j:number)=>j!==i))}>移除</button></div>)}</div>
    <div className="row"><div className="field"><label>出發時間 *</label><input type="time" value={form.start_time} onChange={e=>upd('start_time',e.target.value)} required/></div><div className="field"><label>結束時間 *</label><input type="time" value={form.end_time} onChange={e=>upd('end_time',e.target.value)} required/></div></div>
    <div className="row"><div className="field"><label>出發里程</label><input type="number" min="0" step="1" value={form.start_mileage} onChange={e=>upd('start_mileage',e.target.value)}/><div className="hint">若同車同日已有更早的使用紀錄，後續使用人可不填出發里程。</div></div><div className="field"><label>結束里程 *</label><input type="number" min="0" step="1" value={form.end_mileage} onChange={e=>upd('end_mileage',e.target.value)} required/></div></div>
    <div className="field"><label>用途 *</label><div className="checkboxes">{purposes.map(p=><label key={p.id}><input type="checkbox" checked={form.purpose_ids.includes(p.id)} onChange={()=>toggle(p.id)}/> {p.id}. {p.label}</label>)}</div></div>
    <div className="row"><div className="field"><label>加油時里程（選填）</label><input type="number" min="0" step="1" value={form.fuel_mileage} onChange={e=>upd('fuel_mileage',e.target.value)}/></div><div className="field"><label>加油費（選填）</label><input type="number" min="0" step="1" value={form.fuel_cost} onChange={e=>upd('fuel_cost',e.target.value)}/></div></div>
    <div className="field"><label>備註</label><textarea rows={4} value={form.remarks} onChange={e=>upd('remarks',e.target.value)}/></div><button className="btn primary" disabled={saving}>{saving?'儲存中…':'儲存使用紀錄'}</button>
  </form></main>
}
